// <auto-generated />
using System;
using Gesco_Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gesco_Repository.Migrations
{
    [DbContext(typeof(GescoDbContext))]
    [Migration("20240204212927_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Pocos.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("AddresseClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Entities.Pocos.EnteteFacture", b =>
                {
                    b.Property<int>("IdEnteteFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnteteFacture"));

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdFacture")
                        .HasColumnType("int");

                    b.HasKey("IdEnteteFacture");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdFacture")
                        .IsUnique();

                    b.ToTable("EnteteFacture");
                });

            modelBuilder.Entity("Entities.Pocos.EnteteFactureFournisseur", b =>
                {
                    b.Property<int>("IdEnteteFactureFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnteteFactureFournisseur"));

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFactureFournisseur")
                        .HasColumnType("int");

                    b.Property<int>("IdFournisseur")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceFactureFournisseur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEnteteFactureFournisseur");

                    b.HasIndex("IdFactureFournisseur")
                        .IsUnique();

                    b.HasIndex("IdFournisseur");

                    b.ToTable("EnteteFactureFournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.Facture", b =>
                {
                    b.Property<int>("IdFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacture"));

                    b.Property<string>("ReferenceFacture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFacture");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("Entities.Pocos.FactureFournisseur", b =>
                {
                    b.Property<int>("IdFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFournisseur"));

                    b.HasKey("IdFournisseur");

                    b.ToTable("FactureFournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.Fournisseur", b =>
                {
                    b.Property<int>("IdFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFournisseur"));

                    b.Property<string>("AddresseFournisseur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AddresseFournisseur");

                    b.Property<string>("NomFournisseur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NomFournisseur");

                    b.HasKey("IdFournisseur");

                    b.ToTable("Fournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.LigneFacture", b =>
                {
                    b.Property<int>("IdLigneFacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLigneFacture"));

                    b.Property<int>("IdFacture")
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdLigneFacture");

                    b.HasIndex("IdFacture");

                    b.HasIndex("IdProduit");

                    b.ToTable("LigneFacture");
                });

            modelBuilder.Entity("Entities.Pocos.LigneFactureFournisseur", b =>
                {
                    b.Property<int>("IdLigneFactureFournisseur")
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdLigneFactureFournisseur");

                    b.HasIndex("IdProduit");

                    b.ToTable("LigneFactureFournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrixProduit")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdProduit");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("Entities.Pocos.ProduitFournisseur", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrixProduit")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdProduit");

                    b.ToTable("ProduitFournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStock"));

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLigneFacture")
                        .HasColumnType("int");

                    b.Property<string>("Sens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStock");

                    b.HasIndex("IdLigneFacture");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Entities.Pocos.EnteteFacture", b =>
                {
                    b.HasOne("Entities.Pocos.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Pocos.Facture", "Facture")
                        .WithOne("EnteteFacture")
                        .HasForeignKey("Entities.Pocos.EnteteFacture", "IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Entities.Pocos.EnteteFactureFournisseur", b =>
                {
                    b.HasOne("Entities.Pocos.FactureFournisseur", "FactureFournisseur")
                        .WithOne("EnteteFactureFournisseur")
                        .HasForeignKey("Entities.Pocos.EnteteFactureFournisseur", "IdFactureFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Pocos.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("IdFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureFournisseur");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.LigneFacture", b =>
                {
                    b.HasOne("Entities.Pocos.Facture", "Facture")
                        .WithMany("LigneFacture")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Pocos.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Entities.Pocos.LigneFactureFournisseur", b =>
                {
                    b.HasOne("Entities.Pocos.FactureFournisseur", "FactureFournisseur")
                        .WithMany("LigneFactureFournisseur")
                        .HasForeignKey("IdLigneFactureFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Pocos.ProduitFournisseur", "ProduitFournisseur")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureFournisseur");

                    b.Navigation("ProduitFournisseur");
                });

            modelBuilder.Entity("Entities.Pocos.Stock", b =>
                {
                    b.HasOne("Entities.Pocos.LigneFacture", "LigneFacture")
                        .WithMany()
                        .HasForeignKey("IdLigneFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LigneFacture");
                });

            modelBuilder.Entity("Entities.Pocos.Facture", b =>
                {
                    b.Navigation("EnteteFacture")
                        .IsRequired();

                    b.Navigation("LigneFacture");
                });

            modelBuilder.Entity("Entities.Pocos.FactureFournisseur", b =>
                {
                    b.Navigation("EnteteFactureFournisseur")
                        .IsRequired();

                    b.Navigation("LigneFactureFournisseur");
                });
#pragma warning restore 612, 618
        }
    }
}
